import 'package:equatable/equatable.dart';

/// Represents an authenticated user with profile information.
///
/// Fields like [birthDate], [gender], and [phoneNumber] are nullable to support
/// users in the middle of signup (before profile completion) or users with
/// incomplete profiles.
class UserAuthEntity extends Equatable {
  final String username; // Auto-generated by backend
  final String? nickname; // User-set alias
  final String email;
  // Also provide a DateTime convenience field for presentation code.
  final DateTime? birthDate;
  final int? age;
  final String? gender; // 'M', 'F', 'Other' (nullable)
  final String? phoneNumber; // E.164 format (nullable)
  final bool isVerified; // Email verification status
  final String? accessToken; // JWT access token
  final String? refreshToken; // Refresh token
  // Backwards-compatible aliases used by presentation layer
  final String? password;

  const UserAuthEntity({
    required this.username,
    this.nickname,
    required this.email,
    this.birthDate,
    this.age,
    this.gender,
    this.phoneNumber,
    required this.isVerified,
    this.accessToken,
    this.refreshToken,
    this.password,
  });

  /// Checks if user's profile is complete (has all required fields for post-signup).
  /// Returns true only if DOB, gender, and phone are all present.
  bool get isProfileComplete =>
      birthDate != null && gender != null && phoneNumber != null;

  UserAuthEntity copyWith({
    String? username,
    String? nickname,
    String? email,
    DateTime? birthDate,
    int? age,
    String? gender,
    String? phoneNumber,
    bool? isVerified,
    String? accessToken,
    String? refreshToken,
    String? password,
  }) {
    return UserAuthEntity(
      username: username ?? this.username,
      nickname: nickname ?? this.nickname,
      email: email ?? this.email,
      birthDate: birthDate ?? this.birthDate,
      age: age ?? this.age,
      gender: gender ?? this.gender,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      isVerified: isVerified ?? this.isVerified,
      accessToken: accessToken ?? this.accessToken,
      refreshToken: refreshToken ?? this.refreshToken,
      password: password ?? this.password,
    );
  }

  @override
  List<Object?> get props => [
    username,
    nickname,
    email,
    birthDate,
    age,
    gender,
    phoneNumber,
    isVerified,
    accessToken,
    refreshToken,
    password,
  ];
}
